# Generated by Django 4.0.3 on 2024-09-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
