# Generated by Django 4.0.3 on 2024-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ramen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('initial_count', models.IntegerField(default=0)),
                ('remaining_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PREPARING', '준비 중'), ('COMPLETED', '완료됨')], default='PREPARING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
